### PR TITLE
Fix showTabGroup showing hidden tab + Fix showTab not working when called from show callback

### PR DESCRIPTION
**Pull request by theeban275**
@matthew-intersect please review

### CODE REVIEW

**Comment by theeban275** [comment]
@Denubis if you want to show the first tab when loading a record then you will just need to call showTab in the show event of the tabGroup

**Comment by Denubis** [comment]
This breaks current modules. And how do we differentiate between how the
various tabs are entered in the show event?

**Comment by theeban275** [comment]
Updated fix to keep current behaviour + fix to show first visible tab + override current behaviour using showTab when called from callback triggered from show event of tabgroup

**Comment by matthew-intersect** [comment]
yep, looks good to go

**Pull request merged**
